/**
 * Events: native config generation / merge / teardown for every events
 * format. Ports of tests/specify_cli/events/test_events.py
 * (TestClaudeJsonMerging, TestCopilotJsonWriting, TestCursorJsonWriting,
 * TestDevinRootNestedFormat, TestTomlMatcherEscaping, TestTomlUnreadableConfig,
 * TestTomlNoOpMerge, TestOpencodePluginMerging, TestMergeIdempotency,
 * TestEmptyMapRemoval, TestTeardownDataSafety, TestCopilotMergeTeardown,
 * TestSharedDispatcherRefcount, TestSafeWriteDestination,
 * TestSkippedMergeNotTracked, TestCursorVersionOnlyStubDeletion).
 */

import { afterEach, beforeEach, describe, expect, spyOn, test } from 'bun:test';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';

import {
  EVENTS_DISPATCHER_REL,
  EVENTS_DISPATCHER_TEMPLATE,
  buildOpencodePlugin,
  installIntegrationEvents,
  removeIntegrationEvents,
  type EventManifest,
} from '../src/events/index.js';
import { IntegrationManifest } from '../src/integrations/manifest.js';
import { ClaudeIntegration } from '../src/integrations/claude.js';
import { CodexIntegration } from '../src/integrations/codex.js';
import { CopilotIntegration } from '../src/integrations/copilot.js';
import { CursorAgentIntegration } from '../src/integrations/cursor-agent.js';
import { DevinIntegration } from '../src/integrations/devin.js';
import { GeminiIntegration } from '../src/integrations/gemini.js';
import { OpencodeIntegration } from '../src/integrations/opencode.js';
import { VibeIntegration } from '../src/integrations/vibe.js';

let tmp: string;
let stderrSpy: ReturnType<typeof spyOn>;

beforeEach(() => {
  tmp = realpathSync(mkdtempSync(path.join(tmpdir(), 'events-install-')));
  stderrSpy = spyOn(process.stderr, 'write').mockImplementation(() => true);
});

afterEach(() => {
  stderrSpy.mockRestore();
  rmSync(tmp, { recursive: true, force: true });
});

/** MagicMock(spec=IntegrationManifest) equivalent that records calls. */
function fakeManifest(): EventManifest & {
  files: Record<string, string>;
  calls: { recordFile: string[]; recordExisting: string[]; remove: string[] };
} {
  const calls = { recordFile: [] as string[], recordExisting: [] as string[], remove: [] as string[] };
  return {
    files: {},
    calls,
    recordFile(rel: string) {
      calls.recordFile.push(rel);
    },
    recordExisting(rel: string) {
      calls.recordExisting.push(rel);
    },
    remove(rel: string) {
      calls.remove.push(rel);
    },
  };
}

function readJson(rel: string): any {
  return JSON.parse(readFileSync(path.join(tmp, rel), 'utf8'));
}

function write(rel: string, content: string | Buffer): string {
  const p = path.join(tmp, rel);
  mkdirSync(path.dirname(p), { recursive: true });
  writeFileSync(p, content);
  return p;
}

// ============================================================================
// JSON nested (Claude)
// ============================================================================

describe('json-nested (Claude)', () => {
  test('merge into empty file', () => {
    const manifest = fakeManifest();
    const created = installIntegrationEvents(new ClaudeIntegration(), tmp, manifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate', matcher: 'Edit|Write' }],
    });
    const data = readJson('.claude/settings.json');
    expect(data.hooks.PreToolUse[0].matcher).toBe('Edit|Write');
    const inner = data.hooks.PreToolUse[0].hooks[0];
    expect(typeof inner.command).toBe('string');
    expect(inner.args).toBeUndefined();
    expect(inner.command).toBe('python3 "${CLAUDE_PROJECT_DIR}/.specify/events.py" speckit.tdd.validate pre_tool_use 60');
    expect(inner.timeout).toBe(65);
    expect(inner.__speckit_event__).toBe(true);
    // Dispatcher generated byte-identical and executable.
    const dispatcher = path.join(tmp, EVENTS_DISPATCHER_REL);
    expect(readFileSync(dispatcher, 'utf8')).toBe(EVENTS_DISPATCHER_TEMPLATE);
    expect(statSync(dispatcher).mode & 0o777).toBe(0o755);
    expect(manifest.calls.recordFile).toEqual(['.specify/events.py']);
    expect(manifest.calls.recordExisting).toEqual(['.claude/settings.json']);
    expect(created).toEqual([dispatcher, path.join(tmp, '.claude/settings.json')]);
    // Python json.dumps(indent=2) layout
    expect(readFileSync(path.join(tmp, '.claude/settings.json'), 'utf8')).toBe(
      '{\n  "hooks": {\n    "PreToolUse": [\n      {\n        "matcher": "Edit|Write",\n        "hooks": [\n          {\n' +
        '            "type": "command",\n            "command": "python3 \\"${CLAUDE_PROJECT_DIR}/.specify/events.py\\" speckit.tdd.validate pre_tool_use 60",\n' +
        '            "timeout": 65,\n            "__speckit_event__": true\n          }\n        ]\n      }\n    ]\n  }\n}\n',
    );
  });

  test('all handlers for the same event are emitted (#2)', () => {
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }, { command: 'speckit.other.check' }],
    });
    const cmds = readJson('.claude/settings.json').hooks.PreToolUse.flatMap((g: any) =>
      g.hooks.map((h: any) => h.command),
    );
    expect(cmds.some((c: string) => c.includes('speckit.tdd.validate'))).toBe(true);
    expect(cmds.some((c: string) => c.includes('speckit.other.check'))).toBe(true);
  });

  test('matcher grouping per distinct matcher (S3)', () => {
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [
        { command: 'speckit.first', matcher: 'Edit' },
        { command: 'speckit.second', matcher: 'Bash' },
        { command: 'speckit.third', matcher: 'Edit' },
      ],
    });
    const groups = readJson('.claude/settings.json').hooks.PreToolUse;
    expect(groups.map((g: any) => g.matcher)).toEqual(['Edit', 'Bash']);
    expect(groups[0].hooks).toHaveLength(2);
    expect(groups[1].hooks[0].command).toContain('speckit.second');
  });

  test('remove preserves user hooks', () => {
    write(
      '.claude/settings.json',
      JSON.stringify({
        hooks: { PreToolUse: [{ matcher: 'Bash', hooks: [{ type: 'command', command: 'user-check' }] }] },
        userSetting: true,
      }),
    );
    const manifest = fakeManifest();
    installIntegrationEvents(new ClaudeIntegration(), tmp, manifest, { stop: [{ command: 'speckit.end' }] });
    removeIntegrationEvents(new ClaudeIntegration(), tmp, manifest);
    const data = readJson('.claude/settings.json');
    expect(data.userSetting).toBe(true);
    expect(data.hooks.Stop).toBeUndefined();
    expect(data.hooks.PreToolUse[0].matcher).toBe('Bash');
    expect(manifest.calls.remove).toContain('.claude/settings.json');
  });

  test('upgrade does not duplicate nested hooks (#9) and stale events are removed (#11)', () => {
    const events = { pre_tool_use: [{ command: 'speckit.tdd.validate' }] };
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), events);
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), events);
    const groups = readJson('.claude/settings.json').hooks.PreToolUse;
    expect(groups).toHaveLength(1);
    expect(groups[0].hooks).toHaveLength(1);

    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), { stop: [{ command: 'speckit.end' }] });
    const hooks = readJson('.claude/settings.json').hooks;
    expect(hooks.PreToolUse).toBeUndefined();
    expect(hooks.Stop).toBeDefined();
  });

  test('empty events strip prior hooks (#3) and delete Spec-Kit-only config (#14)', () => {
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    expect(existsSync(path.join(tmp, '.claude/settings.json'))).toBe(true);
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), {});
    expect(existsSync(path.join(tmp, '.claude/settings.json'))).toBe(false);
    // No other integration references the dispatcher → removed too (S3).
    expect(existsSync(path.join(tmp, EVENTS_DISPATCHER_REL))).toBe(false);
  });

  test('JSONC config is not reset and not tracked (#22, S5)', () => {
    const jsonc = '{\n  // my comment\n  "hooks": {}\n}\n';
    write('.claude/settings.json', jsonc);
    const manifest = fakeManifest();
    const created = installIntegrationEvents(new ClaudeIntegration(), tmp, manifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    expect(readFileSync(path.join(tmp, '.claude/settings.json'), 'utf8')).toBe(jsonc);
    expect(manifest.calls.recordExisting).toEqual([]);
    expect(created).toEqual([path.join(tmp, EVENTS_DISPATCHER_REL)]);
    expect(String(stderrSpy.mock.calls.map((c: unknown[]) => c[0]).join(''))).toContain(
      'skipping event-config merge to preserve user content.',
    );
  });

  test('unreadable config (a directory) aborts the merge', () => {
    mkdirSync(path.join(tmp, '.claude/settings.json'), { recursive: true });
    installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    expect(statSync(path.join(tmp, '.claude/settings.json')).isDirectory()).toBe(true);
  });

  test('forced full teardown with a real manifest preserves user config (S9)', () => {
    write(
      '.claude/settings.json',
      JSON.stringify({
        hooks: { PreToolUse: [{ matcher: 'Bash', hooks: [{ type: 'command', command: 'user-check' }] }] },
        userSetting: true,
      }),
    );
    const integration = new ClaudeIntegration();
    const manifest = new IntegrationManifest('claude', tmp, 'test');
    installIntegrationEvents(integration, tmp, manifest, { stop: [{ command: 'speckit.end' }] });
    manifest.save();
    expect(Object.keys(manifest.files)).toContain('.specify/events.py');
    removeIntegrationEvents(integration, tmp, manifest);
    manifest.uninstall(tmp, { force: true });
    const data = readJson('.claude/settings.json');
    expect(data.userSetting).toBe(true);
    expect(data.hooks.PreToolUse[0].matcher).toBe('Bash');
  });
});

// ============================================================================
// Copilot / Cursor / Devin
// ============================================================================

describe('copilot-json', () => {
  test('generation with OS-targeted variants', () => {
    installIntegrationEvents(new CopilotIntegration(), tmp, fakeManifest(), {
      session_start: [{ command: 'speckit.agent-context.update', timeout: 60 }],
    });
    const data = readJson('.github/hooks/speckit.json');
    expect(data.version).toBe(1);
    const entry = data.hooks.sessionStart[0];
    expect(entry.type).toBe('command');
    expect(entry.bash).toBe(
      'python3 .specify/events.py speckit.agent-context.update session_start 60 additionalContext',
    );
    expect(entry.powershell).toBe(
      "& 'python' '.specify/events.py' 'speckit.agent-context.update' 'session_start' '60' 'additionalContext'",
    );
    expect(entry.timeoutSec).toBe(65);
  });

  test('merge preserves user hooks; teardown removes only owned entries', () => {
    write(
      '.github/hooks/speckit.json',
      JSON.stringify({ version: 1, hooks: { sessionStart: [{ type: 'command', bash: 'user-hook' }] } }),
    );
    const manifest = fakeManifest();
    installIntegrationEvents(new CopilotIntegration(), tmp, manifest, { session_start: [{ command: 'speckit.boot' }] });
    const bash = readJson('.github/hooks/speckit.json').hooks.sessionStart.map((e: any) => e.bash);
    expect(bash).toContain('user-hook');
    expect(bash.some((c: string) => c.includes('speckit.boot'))).toBe(true);
    removeIntegrationEvents(new CopilotIntegration(), tmp, manifest);
    expect(readJson('.github/hooks/speckit.json').hooks.sessionStart).toEqual([{ type: 'command', bash: 'user-hook' }]);
  });

  test('teardown deletes Spec-Kit-only file', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new CopilotIntegration(), tmp, manifest, { session_start: [{ command: 'speckit.boot' }] });
    removeIntegrationEvents(new CopilotIntegration(), tmp, manifest);
    expect(existsSync(path.join(tmp, '.github/hooks/speckit.json'))).toBe(false);
  });
});

describe('json-flat (Cursor)', () => {
  test('includes version and preserves user version', () => {
    installIntegrationEvents(new CursorAgentIntegration(), tmp, fakeManifest(), {
      session_start: [{ command: 'speckit.boot' }],
    });
    const data = readJson('.cursor/hooks.json');
    expect(data.version).toBe(1);
    expect(data.hooks.sessionStart[0]).toEqual({
      command: 'python3 .specify/events.py speckit.boot session_start 60 additional_context',
      type: 'command',
      timeout: 65,
      matcher: '*',
      __speckit_event__: true,
    });
  });

  test('version-only stub is deleted on teardown', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new CursorAgentIntegration(), tmp, manifest, { session_start: [{ command: 'speckit.boot' }] });
    removeIntegrationEvents(new CursorAgentIntegration(), tmp, manifest);
    expect(existsSync(path.join(tmp, '.cursor/hooks.json'))).toBe(false);
  });
});

describe('json-root-nested (Devin)', () => {
  test('events written at root; teardown preserves user entries', () => {
    write(
      '.devin/hooks.v1.json',
      JSON.stringify({ PreToolUse: [{ matcher: 'exec', hooks: [{ type: 'command', command: 'user-check' }] }] }),
    );
    const manifest = fakeManifest();
    installIntegrationEvents(new DevinIntegration(), tmp, manifest, { stop: [{ command: 'speckit.end' }] });
    let data = readJson('.devin/hooks.v1.json');
    expect(data.hooks).toBeUndefined();
    expect(data.Stop).toBeDefined();
    removeIntegrationEvents(new DevinIntegration(), tmp, manifest);
    data = readJson('.devin/hooks.v1.json');
    expect(data.Stop).toBeUndefined();
    expect(data.PreToolUse[0].matcher).toBe('exec');
  });
});

describe('ms timeout unit (Gemini)', () => {
  test('native timeout converted, dispatcher arg stays seconds', () => {
    installIntegrationEvents(new GeminiIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [{ command: 'speckit.guard', timeout: 30 }],
    });
    const inner = readJson('.gemini/settings.json').hooks.BeforeTool[0].hooks[0];
    expect(inner.timeout).toBe(35000);
    expect(inner.command).toEndWith(' speckit.guard pre_tool_use 30 suppress');
  });
});

// ============================================================================
// TOML (Codex) and TOML-vibe
// ============================================================================

describe('toml (Codex)', () => {
  test('exact fragment with escaped matcher (R4)', () => {
    installIntegrationEvents(new CodexIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [{ command: 'speckit.x.y', matcher: 'Ba"sh' }],
    });
    expect(readFileSync(path.join(tmp, '.codex/config.toml'), 'utf8')).toBe(
      '\n\n[[hooks.PreToolUse]]\nmatcher = "Ba\\"sh"\n\n[[hooks.PreToolUse.hooks]]\ntype = "command"\n' +
        'command = "python3 .specify/events.py speckit.x.y pre_tool_use 60"\ntimeout = 65\nspeckit_marker = true\n\n',
    );
  });

  test('merge skips unreadable config and preserves bytes', () => {
    const userBytes = Buffer.from('# codex config \xff\xfe not utf-8\n', 'latin1');
    write('.codex/config.toml', userBytes);
    const manifest = fakeManifest();
    installIntegrationEvents(new CodexIntegration(), tmp, manifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    expect(readFileSync(path.join(tmp, '.codex/config.toml')).equals(userBytes)).toBe(true);
    expect(manifest.calls.recordExisting).toEqual([]);
  });

  test('teardown skips unreadable config and preserves bytes', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new CodexIntegration(), tmp, manifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    const userBytes = Buffer.from('# rewritten \xff\xfe not utf-8\n', 'latin1');
    write('.codex/config.toml', userBytes);
    removeIntegrationEvents(new CodexIntegration(), tmp, manifest);
    expect(readFileSync(path.join(tmp, '.codex/config.toml')).equals(userBytes)).toBe(true);
  });

  test('no events leaves existing / comments-only / blank configs untouched (#4563)', () => {
    for (const original of ['project_doc_max_bytes = 200000', '# managed by the user\n# second\n', '\n\n']) {
      const p = write('.codex/config.toml', original);
      const before = statSync(p).mtimeMs;
      const manifest = fakeManifest();
      installIntegrationEvents(new CodexIntegration(), tmp, manifest, {});
      expect(readFileSync(p, 'utf8')).toBe(original);
      expect(statSync(p).mtimeMs).toBe(before);
      expect(manifest.calls.recordExisting).toEqual([]);
    }
  });

  test('owned-only config deleted on teardown; user content preserved', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new CodexIntegration(), tmp, manifest, { pre_tool_use: [{ command: 'speckit.a' }] });
    removeIntegrationEvents(new CodexIntegration(), tmp, manifest);
    expect(existsSync(path.join(tmp, '.codex/config.toml'))).toBe(false);

    write('.codex/config.toml', 'model = "o3"\n');
    installIntegrationEvents(new CodexIntegration(), tmp, manifest, { pre_tool_use: [{ command: 'speckit.a' }] });
    installIntegrationEvents(new CodexIntegration(), tmp, manifest, { stop: [{ command: 'speckit.b' }] });
    const merged = readFileSync(path.join(tmp, '.codex/config.toml'), 'utf8');
    expect(merged.startsWith('model = "o3"\n\n[[hooks.Stop]]')).toBe(true);
    expect(merged).not.toContain('PreToolUse');
    removeIntegrationEvents(new CodexIntegration(), tmp, manifest);
    expect(readFileSync(path.join(tmp, '.codex/config.toml'), 'utf8')).toBe('model = "o3"\n\n');
  });
});

describe('toml-vibe', () => {
  test('unique hook names and re: matchers on tool hooks only', () => {
    installIntegrationEvents(new VibeIntegration(), tmp, fakeManifest(), {
      pre_tool_use: [
        { command: 'speckit.a.validate', matcher: 'Edit|Write' },
        { command: 'speckit.b.validate' },
      ],
      stop: [{ command: 'speckit.end', matcher: 'X' }],
    });
    const text = readFileSync(path.join(tmp, '.vibe/hooks.toml'), 'utf8');
    expect(text).toContain('name = "speckit-pre_tool-validate"\n');
    expect(text).toContain('name = "speckit-pre_tool-validate-2"\n');
    expect(text).toContain('match = "re:Edit|Write"\n');
    expect(text.match(/match = /g)).toHaveLength(1);
    expect(text).toContain('pre_tool_use 60 hook_specific_output"');
  });
});

// ============================================================================
// OpenCode TS plugin
// ============================================================================

describe('ts-plugin (OpenCode)', () => {
  test('plugin generation and opencode.json ref', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new OpencodeIntegration(), tmp, manifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate', matcher: 'Edit|Write' }],
      session_start: [{ command: 'speckit.boot' }],
      user_prompt_submit: [{ command: 'speckit.prompt' }],
      session_end: [{ command: 'speckit.end' }],
    });
    const plugin = readFileSync(path.join(tmp, '.opencode/plugin/speckit-events.ts'), 'utf8');
    expect(plugin).toContain('export default (async ({ client, project, directory, $ }) => {');
    expect(plugin).toContain('resolveDispatcher(directory);');
    expect(plugin).toContain('if (input.tool === "edit" || input.tool === "write")');
    expect(plugin).toContain('"tool.execute.before": async (input: any, output: any) => {');
    expect(plugin).toContain('output.system.push(ctx)');
    expect(plugin).toContain('messageID: output.message.id');
    expect(plugin).toContain('if (event.sessionID) sessionStartCache.delete(event.sessionID); _session_end(event, event);');
    expect(plugin).toContain('timeout: (timeoutSec + 5) * 1000,');
    expect(plugin).toContain('throw new Error(`specify event ${command} (${event}) failed: ${(e as Error).message}`);');
    expect(readJson('opencode.json')).toEqual({ plugin: ['./.opencode/plugin/speckit-events.ts'] });
    expect(manifest.calls.recordFile).toEqual(['.specify/events.py', '.opencode/plugin/speckit-events.ts']);
  });

  test('metacharacters escaped as JSON literals; non-numeric timeout defaults to 60', () => {
    const plugin = buildOpencodePlugin(
      { pre_tool_use: [{ command: 'speckit.x\'"`${evil}`', timeout: 'abc' }] },
      { pre_tool_use: 'tool.execute.before' },
    );
    expect(plugin).toContain('runEvent("speckit.x\'\\"`${evil}`", "pre_tool_use", input, output, 60)');
  });

  test('malformed opencode.json is not reset (#23)', () => {
    write('opencode.json', '{ not valid json');
    installIntegrationEvents(new OpencodeIntegration(), tmp, fakeManifest(), {
      session_start: [{ command: 'speckit.boot' }],
    });
    expect(readFileSync(path.join(tmp, 'opencode.json'), 'utf8')).toBe('{ not valid json');
  });

  test('teardown removes plugin ref and plugin file', () => {
    write('opencode.json', JSON.stringify({ theme: 'dark' }));
    const manifest = fakeManifest();
    installIntegrationEvents(new OpencodeIntegration(), tmp, manifest, { session_start: [{ command: 'speckit.boot' }] });
    manifest.files['.opencode/plugin/speckit-events.ts'] = 'hash';
    removeIntegrationEvents(new OpencodeIntegration(), tmp, manifest);
    expect(readJson('opencode.json')).toEqual({ theme: 'dark' });
    expect(existsSync(path.join(tmp, '.opencode/plugin/speckit-events.ts'))).toBe(false);
  });
});

// ============================================================================
// Shared dispatcher refcount & destination safety
// ============================================================================

describe('shared dispatcher refcount (#10)', () => {
  test('dispatcher kept when another installed integration references it', () => {
    const claudeManifest = fakeManifest();
    installIntegrationEvents(new ClaudeIntegration(), tmp, claudeManifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    const codexDisk = new IntegrationManifest('codex', tmp, 'test');
    codexDisk.recordExisting(EVENTS_DISPATCHER_REL);
    codexDisk.save();
    write(
      '.specify/integration.json',
      JSON.stringify({ default_integration: 'claude', installed_integrations: ['claude', 'codex'] }),
    );
    removeIntegrationEvents(new ClaudeIntegration(), tmp, claudeManifest);
    expect(existsSync(path.join(tmp, EVENTS_DISPATCHER_REL))).toBe(true);
  });

  test('dispatcher deleted for the last integration', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new ClaudeIntegration(), tmp, manifest, {
      pre_tool_use: [{ command: 'speckit.tdd.validate' }],
    });
    removeIntegrationEvents(new ClaudeIntegration(), tmp, manifest);
    expect(existsSync(path.join(tmp, EVENTS_DISPATCHER_REL))).toBe(false);
  });
});

describe('safe write destination (#12)', () => {
  test('symlinked config dir rejected', () => {
    mkdirSync(path.join(tmp, 'outside'));
    symlinkSync(path.join(tmp, 'outside'), path.join(tmp, '.claude'));
    expect(() =>
      installIntegrationEvents(new ClaudeIntegration(), tmp, fakeManifest(), {
        pre_tool_use: [{ command: 'speckit.tdd.validate' }],
      }),
    ).toThrow(/symlink/i);
    expect(existsSync(path.join(tmp, 'outside', 'settings.json'))).toBe(false);
  });

  test('TOML and JSON teardown reject symlinked configs (R3)', () => {
    const manifest = fakeManifest();
    installIntegrationEvents(new CodexIntegration(), tmp, manifest, { pre_tool_use: [{ command: 'speckit.a' }] });
    const cfg = path.join(tmp, '.codex/config.toml');
    const outside = write('outside.toml', 'external = true\n');
    unlinkSync(cfg);
    symlinkSync(outside, cfg);
    expect(() => removeIntegrationEvents(new CodexIntegration(), tmp, manifest)).toThrow(/symlink/i);
    expect(readFileSync(outside, 'utf8')).toBe('external = true\n');

    installIntegrationEvents(new ClaudeIntegration(), tmp, manifest, { pre_tool_use: [{ command: 'speckit.a' }] });
    const settings = path.join(tmp, '.claude/settings.json');
    const outsideJson = write('outside.json', '{"external": true}');
    unlinkSync(settings);
    symlinkSync(outsideJson, settings);
    expect(() => removeIntegrationEvents(new ClaudeIntegration(), tmp, manifest)).toThrow(/symlink/i);
    expect(readFileSync(outsideJson, 'utf8')).toBe('{"external": true}');
  });
});

describe('unsupported events', () => {
  test('unsupported canonical events are skipped with a warning', () => {
    installIntegrationEvents(new VibeIntegration(), tmp, fakeManifest(), {
      session_end: [{ command: 'speckit.end' }],
      pre_tool_use: [{ command: 'speckit.a' }],
    });
    const err = stderrSpy.mock.calls.map((c: unknown[]) => String(c[0])).join('');
    expect(err).toContain("\u26a0\ufe0f  vibe does not support 'session_end' events; skipping\n");
  });
});
