/**
 * Golden-file parity tests for integration rendering.
 *
 * Fixtures under tests/fixtures/integrations/ were generated by running the
 * real upstream Python spec-kit v1.0.12 (`IntegrationBase.setup()` for each
 * representative integration, plus unit-level renderers). The TS port must
 * produce byte-identical output for the same inputs.
 */

import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { mkdtempSync, readdirSync, readFileSync, realpathSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';

import { getIntegration } from '../src/integrations/index.js';
import { IntegrationManifest } from '../src/integrations/manifest.js';
import {
  IntegrationBase,
  SkillsIntegration,
  TomlIntegration,
  YamlIntegration,
  captureWarnings,
  injectArgumentHint,
  injectFrontmatterFlag,
  yamlQuote,
} from '../src/integrations/base.js';
import { CommandRegistrar } from '../src/agents.js';

const FIXTURES = join(import.meta.dir, 'fixtures', 'integrations');

function listFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      const st = statSync(p);
      if (st.isDirectory()) walk(p);
      else if (st.isFile()) out.push(relative(root, p).split('\\').join('/'));
    }
  };
  walk(root);
  return out.sort();
}

interface SetupFixture {
  key: string;
  parsed_options: Record<string, unknown> | null;
  files: Record<string, string>;
  created: string[];
  manifest_files: string[];
}

let tmp: string;
let home: string;
const savedHome = process.env.HOME;

beforeEach(() => {
  tmp = realpathSync(mkdtempSync(join(tmpdir(), 'speckit-render-')));
  home = realpathSync(mkdtempSync(join(tmpdir(), 'speckit-home-')));
  process.env.HOME = home;
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
  rmSync(home, { recursive: true, force: true });
  process.env.HOME = savedHome;
});

// ============================================================================
// setup() golden parity
// ============================================================================

describe('setup() output matches upstream byte-for-byte', () => {
  const fixtureFiles = readdirSync(FIXTURES).filter((f) => f.startsWith('setup-') && f.endsWith('.json')).sort();

  test('fixtures are present', () => {
    expect(fixtureFiles.length).toBeGreaterThanOrEqual(25);
  });

  for (const file of fixtureFiles) {
    const fixture = JSON.parse(readFileSync(join(FIXTURES, file), 'utf-8')) as SetupFixture;
    test(`${file.replace(/^setup-|\.json$/g, '')}`, () => {
      const integration = getIntegration(fixture.key)!;
      expect(integration).not.toBeNull();
      const manifest = new IntegrationManifest(fixture.key, tmp, '1.0.12');
      const [created] = captureWarnings(() =>
        integration.setup(tmp, manifest, fixture.parsed_options, { scriptType: 'sh', events: {} }),
      );
      const actualFiles = listFiles(tmp);
      expect(actualFiles).toEqual(Object.keys(fixture.files).sort());
      for (const rel of actualFiles) {
        expect({ rel, content: readFileSync(join(tmp, rel), 'utf-8') }).toEqual({ rel, content: fixture.files[rel] });
      }
      const createdRel = created
        .map((p) => relative(tmp, realpathSync(p)).split('\\').join('/'))
        .filter((p) => !p.startsWith('..'))
        .sort();
      expect(createdRel).toEqual(fixture.created);
      expect(Object.keys(manifest.files).sort()).toEqual(fixture.manifest_files);
    });
  }
});

// ============================================================================
// Unit-level renderer parity
// ============================================================================

const units = JSON.parse(readFileSync(join(FIXTURES, 'units.json'), 'utf-8')) as Record<string, unknown[][]>;

describe('yaml_quote parity', () => {
  for (const [input, expected] of units.yaml_quote as [string, string][]) {
    test(JSON.stringify(input), () => {
      expect(yamlQuote(input)).toBe(expected);
    });
  }
});

describe('TOML rendering parity', () => {
  test('_render_toml_string', () => {
    for (const [input, expected] of units.toml_string as [string, string][]) {
      expect({ input, out: TomlIntegration.renderTomlString(input) }).toEqual({ input, out: expected });
    }
  });
  test('_render_toml', () => {
    for (const [d, b, expected] of units.render_toml as [string, string, string][]) {
      expect(TomlIntegration.renderToml(d, b)).toBe(expected);
    }
  });
  test('CommandRegistrar.render_toml_command', () => {
    const reg = new CommandRegistrar();
    for (const [fm, b, expected] of units.registrar_toml as [Record<string, unknown>, string, string][]) {
      expect(reg.renderTomlCommand(fm, b, 'src')).toBe(expected);
    }
  });
});

describe('YAML recipe rendering parity', () => {
  test('_render_yaml', () => {
    for (const [t, d, b, expected] of units.render_yaml as [string, string, string, string][]) {
      expect(YamlIntegration.renderYaml(t, d, b, 'templates/commands/x.md')).toBe(expected);
    }
  });
  test('_human_title', () => {
    for (const [s, expected] of units.human_title as [string, string][]) {
      expect(YamlIntegration.humanTitle(s)).toBe(expected);
    }
  });
});

describe('path rewriting and command refs parity', () => {
  test('rewrite_project_relative_paths', () => {
    for (const [p, ext, expected] of units.rewrite_paths as [string, string | null, string][]) {
      expect({ p, ext, out: CommandRegistrar.rewriteProjectRelativePaths(p, ext) }).toEqual({ p, ext, out: expected });
    }
  });
  test('rewriting is idempotent', () => {
    for (const [p, ext] of units.rewrite_paths as [string, string | null, string][]) {
      const once = CommandRegistrar.rewriteProjectRelativePaths(p, ext);
      expect(CommandRegistrar.rewriteProjectRelativePaths(once, ext)).toBe(once);
    }
  });
  test('resolve_command_refs', () => {
    for (const [r, sep, pre, expected] of units.command_refs as [string, string, string, string][]) {
      expect(IntegrationBase.resolveCommandRefs(r, sep, pre)).toBe(expected);
    }
  });
});

describe('frontmatter injection parity', () => {
  test('inject_argument_hint (fold-aware, CRLF-preserving, idempotent)', () => {
    for (const [d, h, expected] of units.argument_hint as [string, string, string][]) {
      expect({ d, out: injectArgumentHint(d, h) }).toEqual({ d, out: expected });
    }
  });
  test('_inject_frontmatter_flag (newline fix)', () => {
    for (const [d, expected] of units.frontmatter_flag as [string, string][]) {
      expect({ d, out: injectFrontmatterFlag(d, 'user-invocable') }).toEqual({ d, out: expected });
    }
  });
  test('_inject_hook_command_note', () => {
    for (const [d, pre, expected] of units.hook_note as [string, string, string][]) {
      expect({ d, pre, out: SkillsIntegration.injectHookCommandNote(d, pre) }).toEqual({ d, pre, out: expected });
    }
  });
});

describe('frontmatter parse/render parity', () => {
  test('parse_frontmatter', () => {
    for (const [d, expected] of units.parse_frontmatter as [string, [Record<string, unknown>, string]][]) {
      expect({ d, out: CommandRegistrar.parseFrontmatter(d) }).toEqual({ d, out: expected });
    }
  });
  test('render_frontmatter', () => {
    for (const [fm, expected] of units.render_frontmatter as [Record<string, unknown>, string][]) {
      expect(CommandRegistrar.renderFrontmatter(fm)).toBe(expected);
    }
  });
});

describe('process_template parity', () => {
  test('script selection, placeholder and ref substitution', () => {
    for (const [t, agent, st, arg, sep, expected] of units.process_template as [string, string, string, string, string, string][]) {
      expect({ agent, st, out: IntegrationBase.processTemplate(t, agent, st, arg, sep) }).toEqual({ agent, st, out: expected });
    }
  });
});
